Repository Leo-Corporation/Gavilya, pull requests merged in 2022-06, with the labels that each got.

#243 Updated Simplified Chinese translation
  Gavilya/Properties/Resources.zh-CN.resx
Labels: translation, roadmap, vNext

#244 Version 2.6.0.2206
  Gavilya.Setup/Setup.iss
  Gavilya/App.xaml
  Gavilya/Classes/Definitions.cs
  Gavilya/Classes/Global.cs
  Gavilya/Classes/Settings.cs
  Gavilya/Gavilya.csproj
  Gavilya/MainWindow.xaml
  Gavilya/MainWindow.xaml.cs
  Gavilya/Pages/GameInfoPage.xaml.cs
  Gavilya/Pages/GamesCardsPages.xaml.cs
  Gavilya/Pages/SettingsPages/DataOptionsPage.xaml.cs
  Gavilya/Pages/SettingsPages/HomeOptionsPage.xaml
  Gavilya/Pages/SettingsPages/HomeOptionsPage.xaml.cs
  Gavilya/Pages/SettingsPages/LanguagePage.xaml.cs
  Gavilya/Properties/Resources.Designer.cs
  Gavilya/Properties/Resources.en-US.resx
  Gavilya/Properties/Resources.fr-FR.resx
  Gavilya/Properties/Resources.resx
  Gavilya/Properties/Resources.zh-CN.resx
  Gavilya/UserControls/FavoriteGameCard.xaml.cs
  Gavilya/UserControls/GameCard.xaml.cs
  Gavilya/UserControls/GameItem.xaml.cs
  Gavilya/UserControls/SearchItem.xaml
  Gavilya/UserControls/SearchItem.xaml.cs
  Gavilya/Windows/PopupMenu.xaml
  Gavilya/Windows/PopupMenu.xaml.cs
Labels: enhancement, roadmap, vNext

#247 Version 2.6.1.2206
  Gavilya.Setup/Setup.iss
  Gavilya/Classes/Definitions.cs
  Gavilya/Gavilya.csproj
  Gavilya/Pages/AddEditPage.xaml.cs
  Gavilya/Pages/GameInfoPage.xaml.cs
  Gavilya/Pages/ProfilePage.xaml.cs
  Gavilya/UserControls/FavoriteGameCard.xaml.cs
  Gavilya/UserControls/GameCard.xaml.cs
  Gavilya/UserControls/SearchItem.xaml.cs
  Gavilya/UserControls/StatGameInfoControl.xaml.cs
Labels: bug, vNext
